from .connection import get_db
from .schema import init_schema, migrate_schema
from .queries import (
    get_or_create_topic,
    get_all_topics,
    get_all_topics_with_counts,
    get_topic_by_name,
    add_qa_entry,
    get_qa_entry,
    get_recent_qa_entries,
    get_qa_entries_by_topic,
    get_qa_entries_by_topic_id,
    mark_entry_outdated,
    update_qa_entry,
    get_all_qa_entries,
    update_user_knowledge,
    get_user_knowledge,
    get_user_topics,
    add_outdated_flag,
    get_pending_outdated_flags,
    resolve_outdated_flag,
    save_review_summary,
    get_latest_review_summary,
    get_review_summaries,
    get_knowledge_graph,
    get_new_entries_today,
    get_or_create_tag,
    get_all_tags,
    get_tags_for_entry,
    set_tags_for_entry,
    get_entries_by_tag,
    delete_unused_tags,
    find_similar_tags,
    merge_tags,
)
